name: Release
on:
  push:
    tags:
      - '*'

jobs:
  build_for_release:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build_for_release
    permissions:
      contents: write
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          files: "*/*Release*.zip"
          fail_on_unmatched_files: true
